#!/bin/bash
#
# Postgres online backup: post-snapshot script
#
# Unfreezes Postgres database filesystem and releases Postgres from "online backup" state.
# pg_stop_backup() archives all neccesary WAL files and produces "/var/lib/pgsql/9.1/data/pg_xlog/xxxxxxxxxxxxxxxxxxxxxxxx.yyyyyyyy.backup" file
#
# Matvey Marinin 2013
#
# Usage: pgsql-postflash-cmd [-d <db data mount point>] [-p <db port>]
#
# default <db data mount point> = /var/lib/pgsql/9.1/data
# default <db port> = 5432
#
# Script usually runs as "postgres" uid, so it needs permission to "sudo /sbin/fsfreeze" (see /etc/sudoers.d/06_fcm)
#
# NOTE: if "fsfreeze -u" command fail, Postgres will hang forever!!! Fix with "fsfreeze -u /var/lib/pgsql/9.1/data" as root.
#
# v2 - skip pg_start_backup()/pg_stop_backup() if server is stopped
# v3 - pg_port and filesystem parameters
# v4 - posix-style arguments to workaround PRE_FLASH_CMD/POST_FLASH_CMD limitations
#

### There is no need to recover from errors, just exit  ###
set -e

function usage() {
  echo "Usage: $0 [-d <db data mount point>] [-p <db port>]" 1>&2
  exit 1
}

while getopts ":d:p:" o; do
    case "${o}" in
        d)
            #pg data mount point
            FILESYSTEM=${OPTARG}
            ;;
        p)
            #pg port
            PG_PORT=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

[[ -z "$FILESYSTEM" ]] && FILESYSTEM=/var/lib/pgsql/9.1/data
[[ -z "$PG_PORT" ]] && PG_PORT=5432

echo "Running $(basename $0) as UID $EUID, filesystem $FILESYSTEM, pg_port $PG_PORT"

### Unfreeze filesystem ###

echo "Unfreezing filesystem $FILESYSTEM"
if (( $EUID == 0 )); then
  fsfreeze -u "$FILESYSTEM"
else
  sudo fsfreeze -u "$FILESYSTEM"
fi

### Find uid of "postgres" user ###
PG_UID=$(id -u postgres)
if (( $? != 0 )); then
  echo "Cant get uid of postgres user" 1>&2
  exit 1
fi

### Run pg_stop_backup()  ###
echo "Running pg_stop_backup()..."
if (( $EUID == "$PG_UID" )); then
  psql -p "$PG_PORT" -t -c "SELECT pg_stop_backup();" || /bin/true
else
  sudo -u postgres psql -p "$PG_PORT" -t -c "SELECT pg_stop_backup();" || /bin/true
fi
echo "pg_stop_backup() finished"


