#!/bin/bash
#
# TSM client package uploader
#  
# Unpacks TSM BA client distributive and updates Spacewalk repo
#
# Matvey Marinin 2014
#
# v2 - removed download fuctionality
#

if [ $# -ne 1 ]
then
  echo "Usage: $(basename $0) <TSMBAC-xxx.tar>"
  exit 1
fi

TMPDIR=$(mktemp -d)
TARFILE=$1
TMPTAR="$TMPDIR"/$(basename "$TARFILE")

echo "Temp dir: $TMPDIR"
cp -f "$TARFILE" "$TMPTAR"

# cd to temp dir
pushd "$TMPDIR" > /dev/null

#setup trap to cleanup temp dir on exit
trap 'echo "Cleaning up $TMPDIR"; popd > /dev/null; rm -rf "$TMPDIR";' INT TERM EXIT

echo Unpacking "$TMPTAR"
tar xvf "$TMPTAR"

REPO=tsm-client-x64
REPO_ADMIN=tsm-repo-uploader
REPO_ADMIN_PWD=N72bdsG26xkbFz

find "$TMPDIR" -iname '*.rpm' | xargs rhnpush -v --nosig --tolerant --channel="$REPO" --server=http://localhost/APP -u "$REPO_ADMIN" -p "$REPO_ADMIN_PWD"



